### ISSUE TITLE
Where is the root directory supposed to be for saving this file?

### ISSUE THREAD

**Issue by SelfSufficient08** [ajsap/privatebin-yourls#1]
Is it the srv/ directory or the var/www?

**Comment by ajsap** [comment]
You can place it in the _public folder_ of your root Pastebin instance. If you're using shared web hosting, this is typically located at **/home/username/public_html**. For dedicated web server instances, the folder is usually **/var/www/**.

**Comment by SelfSufficient08** [comment]
Thanks !  That makes sense.  I am running in docker so I just need to map a volume for that directory.  I am not a developer but if you put the php script in the public html directory, do you specify special permissions to prevent the public from viewing the php that would hold hold the signature for yourls?  Not sure that it matters but figured I would make sure I am aware.  Thanks for the responses. !

**Comment by ajsap** [comment]
The permissions for your PHP scripts depend on your setup. If you're running PHP with php-fpm, typically, your script files should be owned by the user that php-fpm process runs as, and not writable by other users. This helps to limit access. For Docker, ensure the volume mounts respect these ownership and permission rules. Check the Dockerfile and docker-compose.yml for explicit settings that align with your security requirements. Cheers!
